version: "3.0"
services:
  dsomm: &dsomm
    build: .
    volumes:
    - .:/var/www/html
    working_dir: /var/www/html
    ports:
    - "8082:80"
    environment:
      - ENFORCE_DATA_GENERATION_DURING_RUNTIME="true" 
  test-php:
    <<: *dsomm
    volumes:
    - .:/var/www/html
    ports: []
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/tests.sh"]
