# yaml-language-server: $schema=../../schemas/dsomm-schema-implementation.json
---
Implementation:
  Application Hardening:
    App. Hardening Level 1 (50%):
      uuid: b597928e-54d6-48a5-a806-8003dcd56aab
      risk:
        Using an insecure application might lead to a compromised application.
        This might lead to total data theft or data modification.
      measure: |
        Following frameworks like the
        * OWASP Application Security Verification Standard Level 1
        * OWASP Mobile Application Security Verification Standard

        in all applications provides a good baseline. Implement 50% of the recommendations.
      difficultyOfImplementation:
        knowledge: 2
        time: 2
        resources: 1
      usefulness: 3
      level: 1
      description: |
        To tackle the security of code developed in-house, OWASP offers an extensive collection of [Cheatsheets](https://cheatsheetseries.owasp.org/) demonstrating how to implement features securely. Moreover, the Security Knowledge Framework[1] offers an extensive library of code patterns spanning several programming languages. These patterns can be used to not only jumpstart the development process, but also do so securely.

        [...]

        ### Planning aka Requirements Gathering & Analysis
        The Requirements gathering process tries to answer the question: _"What is the system going to do?"_ At this stage, the [SAMM project](https://owaspsamm.org/model/) offers 3 distinct maturity levels covering both [in-house](https://owaspsamm.org/model/design/security-requirements/stream-a/) software development and [third party](https://owaspsamm.org/model/design/security-requirements/stream-b/) supplier security.

        ![SAMM Requirements](https://github.com/OWASP/www-project-integration-standards/raw/master/writeups/owasp_in_sdlc/images/OWASP-in0.png)

        Organizations can use these to add solid security considerations at the start of the Software Development or Procurement process.

        These general security considerations can be audited by using a subsection of the ASVS controls in section V1 as a questionnaire. This process attempts to ensure that every feature has concrete security considerations.

        In case of internal development and if the organization maps Features to Epics, the [Security Knowledge Framework](https://securityknowledgeframework.org/) can be used to facilitate this process by leveraging its questionnaire function, shown below.

        Source: [OWASP Project Integration](https://raw.githubusercontent.com/OWASP/www-project-integration-standards/master/writeups/owasp_in_sdlc/index.md)
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-asvs
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-masvs
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/apimaturity
      references:
        samm2:
          - D-SR-1-A
        iso27001-2017:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 13.1.3
        iso27001-2022:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 8.22
      isImplemented: false
      evidence: ""
      comments: ""
    App. Hardening Level 1:
      uuid: cf819225-30cb-4702-8e32-60225eedc33d
      risk:
        Using an insecure application might lead to a compromised application.
        This might lead to total data theft or data modification.
      measure: |
        Following frameworks like the
        * OWASP Application Security Verification Standard Level 1
        * OWASP Mobile Application Security Verification Standard

        in all applications provides a good baseline. Implement 95%-100% of the recommendations.
      difficultyOfImplementation:
        knowledge: 2
        time: 2
        resources: 1
      usefulness: 4
      level: 2
      dependsOn:
        - App. Hardening Level 1 (50%)
      description: |
        To tackle the security of code developed in-house, OWASP offers an extensive collection of [Cheatsheets](https://cheatsheetseries.owasp.org/) demonstrating how to implement features securely. Moreover, the Security Knowledge Framework[1] offers an extensive library of code patterns spanning several programming languages. These patterns can be used to not only jump-start the development process, but also do so securely.

        [...]

        ### Planning aka Requirements Gathering & Analysis
        The Requirements gathering process tries to answer the question: _"What is the system going to do?"_ At this stage, the [SAMM project](https://owaspsamm.org/model/) offers 3 distinct maturity levels covering both [in-house](https://owaspsamm.org/model/design/security-requirements/stream-a/) software development and [third party](https://owaspsamm.org/model/design/security-requirements/stream-b/) supplier security.

        ![SAMM Requirements](https://github.com/OWASP/www-project-integration-standards/raw/master/writeups/owasp_in_sdlc/images/OWASP-in0.png)

        Organizations can use these to add solid security considerations at the start of the Software Development or Procurement process.

        These general security considerations can be audited by using a subsection of the ASVS controls in section V1 as a questionnaire. This process attempts to ensure that every feature has concrete security considerations.

        In case of internal development and if the organization maps Features to Epics, the [Security Knowledge Framework](https://securityknowledgeframework.org/) can be used to facilitate this process by leveraging its questionnaire function, shown below.

        Source: [OWASP Project Integration](https://raw.githubusercontent.com/OWASP/www-project-integration-standards/master/writeups/owasp_in_sdlc/index.md)
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-asvs
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-masvs
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/apimaturity
      references:
        samm2:
          - D-SR-1-A
        iso27001-2017:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 13.1.3
        iso27001-2022:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 8.22
      isImplemented: false
      evidence: ""
      comments: ""
    App. Hardening Level 2 (75%):
      uuid: 03643ca2-03c2-472b-8e19-956bf02fe9b7
      risk:
        Using an insecure application might lead to a compromised application.
        This might lead to total data theft or data modification.
      measure: |
        Following frameworks like the
        * OWASP Application Security Verification Standard Level 2
        * OWASP Mobile Application Security Verification Standard Level 2

        Implement 75% of the recommendations.
      difficultyOfImplementation:
        knowledge: 3
        time: 3
        resources: 1
      usefulness: 3
      level: 3
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-asvs
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-masvs
      references:
        samm2:
          - D-SR-2-A
        iso27001-2017:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 13.1.3
        iso27001-2022:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 8.22
      isImplemented: false
      evidence: ""
      comments: ""
      dependsOn:
        - App. Hardening Level 1
    App. Hardening Level 2:
      uuid: ffe86caf-2fec-4630-b514-2db83983984d
      risk:
        Using an insecure application might lead to a compromised application.
        This might lead to total data theft or data modification.
      measure: |
        Following frameworks like the
        * OWASP Application Security Verification Standard Level 2
        * OWASP Mobile Application Security Verification Standard Level 2

        Implement 95%-100% of the recommendations.
      difficultyOfImplementation:
        knowledge: 3
        time: 3
        resources: 1
      usefulness: 3
      level: 4
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-asvs
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-masvs
      references:
        samm2:
          - D-SR-2-A
        iso27001-2017:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 13.1.3
        iso27001-2022:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 8.22
      isImplemented: false
      evidence: ""
      comments: ""
      dependsOn:
        - App. Hardening Level 2 (75%)
    App. Hardening Level 3:
      uuid: 4cae98c2-4163-44ed-bb88-3c67c569533a
      risk:
        Using an insecure application might lead to a compromised application.
        This might lead to total data theft or data modification.
      measure: |
        Following frameworks like the
        * OWASP Application Security Verification Standard Level 3
        * OWASP Mobile Application Security Verification Standard

        Implement 95%-100% of the recommendations.
      difficultyOfImplementation:
        knowledge: 4
        time: 4
        resources: 2
      usefulness: 4
      level: 5
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-asvs
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/owasp-masvs
      references:
        samm2:
          - D-SR-3-A
        iso27001-2017:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 13.1.3
        iso27001-2022:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 8.22
      isImplemented: false
      evidence: ""
      comments: ""
      dependsOn:
        - App. Hardening Level 2
    Usage of a Web Application Firewall:
      uuid: 3e6253ab-89e5-4dea-aca0-3e770b78d39e
      risk:
        Using an insecure application might lead to a compromised application.
        This might lead to total data theft or data modification.
      measure: |
        The usage of an API Gateway / Web Application Firewall might mitigate it. There are debates on how useful a WAF is for APIs.
      difficultyOfImplementation:
        knowledge: 4
        time: 4
        resources: 4
      usefulness: 2
      level: 5
      implementation:
        - $ref: src/assets/YAML/default/implementations.yaml#/implementations/apiMyth
      references:
        samm2:
          - D-SR-3-A
        iso27001-2017:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 13.1.3
        iso27001-2022:
          - Hardening is not explicitly covered by ISO 27001 - too specific
          - 8.22
      isImplemented: false
      evidence: ""
      comments: ""
      dependsOn:
        - App. Hardening Level 2
